// =====================================================================
//  Segway Ninebot Max G3 - 20s4p 21700 cell holder (EVE 40P)
//  Envelope 141 x 270 x 81 mm, fits in front of the deck divider,
//  BMS goes on the other side of the divider.
//
//  Cell layout, copper pieces, tab positions and wire grooves come from
//  layout_data.scad, generated by ../generator/layout.py.
//
//  Coordinates: x = 270 mm length, x = 0 is the DIVIDER end
//               y = 141 mm width,  y = 0 is the side wall the screw post
//                                   is measured from (80 mm)
//               z = height,         z = 0 is the deck floor
//
//  Parts (set `part`, or use the Makefile / export script):
//    holder_bottom, holder_top        cell holder halves (one piece, 270 mm)
//    holder_bottom_a/_b, holder_top_a/_b   same, split for beds < 270 mm
//    lid_bottom, lid_top              insulating cover plates with tab slots
//    lid_bottom_a/_b, lid_top_a/_b    same, split
//    assembly                         everything in place (preview only)
// =====================================================================
include <layout_data.scad>

part = "assembly";

/* [Cell] */
cell_d     = 21.15;   // EVE 40P datasheet: 21.15 +-0.10
cell_len   = 70.6;    // 70.15 +0.15 max + fish-paper ring + margin
cell_bore  = 21.6;    // socket bore: 21.15 cell + 0.45 (0.6 mm web at 22.2 pitch). Also in layout.py
window_d   = 17.0;    // opening in the lip for welding. Also in layout.py

/* [Holder] */
lip        = 1.0;     // end stop the cell sits against (copper bends into window)
sock       = 12.0;    // socket depth per half
rim_h      = 0.8;     // perimeter rim above the lip = room for copper + nickel
rim_w      = 2.0;
peg_hole_d = 4.4;     // locating peg holes in the lip (end voids)
void_d     = 10.0;    // lightening pocket in the end voids (tie anchors)
tie_w      = 4.6;     // zip-tie slot through the end wall (fits 3.6 mm ties)
tie_h      = 2.0;
lead_clear = 1.0;     // clearance each side of the main lead tongues (B-, B+)

/* [Cover plates] */
lid_t      = 2.8;
groove_d   = 1.7;     // balance wire grooves (22-24 AWG silicone)
tab_slot   = [7.0, 3.2];
peg_d      = 4.0;
lead_notch = 10.0;    // depth of the B-/B+ notch in the top lid (x)
text_d     = 0.5;     // engraved labels

/* [Screw post] */
post_clear = 1.0;     // radial clearance
post_extra = 1.0;     // height clearance

/* [Quality] */
$fn = 48;

// ---------------------------------------------------------------------
L = pack_l;
W = pack_w;
half_h   = rim_h + lip + sock;
total_h  = cell_len + 2 * (lid_t + rim_h + lip);
gap_h    = cell_len - 2 * sock;
post_xy  = [post[0], post[1]];
post_d   = post[2];
post_h   = post[3];
tie_z    = rim_h + lip + sock - 3.0 - tie_h;   // tie slot (local z, from rim)
echo(str("TOTAL HEIGHT = ", total_h, " mm (limit 81)  gap between halves = ", gap_h));
assert(total_h <= 81, "pack taller than 81 mm - reduce lid_t / rim_h / lip");

// ---------------------------------------------------------------------
// 2D helpers
// ---------------------------------------------------------------------
module outline() { square([L, W]); }

module split_mask(which) {
    // which: "all", "a", "b"   (holder: zig-zag between cells)
    if (which == "a") polygon(split_a);
    else if (which == "b") difference() { translate([-1, -1]) square([L + 2, W + 2]); polygon(split_a); }
    else translate([-1, -1]) square([L + 2, W + 2]);
}

module lid_mask(which) {
    // lids are split straight at lid_split_x (away from the holder seam)
    if (which == "a") translate([-1, -1]) square([lid_split_x + 1, W + 2]);
    else if (which == "b") translate([lid_split_x, -1]) square([L, W + 2]);
    else translate([-1, -1]) square([L + 2, W + 2]);
}

module bores()   { for (c = cells) translate([c[0], c[1]]) circle(d = cell_bore); }
module windows() { for (c = cells) translate([c[0], c[1]]) circle(d = window_d); }
module chase2d() { translate(chase) circle(d = cell_bore); }
module post2d()  {   // open towards the divider end so it never grazes the wall
    hull() for (dx = [0, -post_xy[0] - 1]) translate(post_xy + [dx, 0]) circle(d = post_d + 2 * post_clear);
}
module voids()   { for (v = concat(voids_x0, voids_x1)) translate(v) circle(d = void_d); }
module peg_holes() { for (v = concat(voids_x0, voids_x1)) translate(v) circle(d = peg_hole_d); }
module lead_gaps() { for (l = leads) translate([-1, l[0] - l[2] / 2 - lead_clear]) square([rim_w + 6, l[2] + 2 * lead_clear]); }
module tie_slots() {
    for (v = voids_x0) translate([-1, v[1] - tie_w / 2]) square([v[0], tie_w]);
}

// 3D slab: linear_extrude a 2D region between z0 and z1
module slab(z0, z1) { translate([0, 0, z0]) linear_extrude(z1 - z0) children(); }

// ---------------------------------------------------------------------
// Holder half. Local coords: z = 0 is the rim face (towards the lid),
// xy = world xy. Print in this orientation (rim down, no supports).
// ---------------------------------------------------------------------
module holder_half(face = "bottom", which = "all") {
    zl = rim_h;                 // lip starts
    zs = rim_h + lip;           // sockets start
    zt = half_h;                // inner end
    // screw post pocket height in local coords (bottom half only)
    zp = (face == "bottom") ? min(zt, post_h + post_extra - lid_t) : -1;

    module socket_layer(cut_post, cut_tie) {
        intersection() {
            split_mask(which);
            difference() {
                outline();
                bores();
                chase2d();
                voids();
                if (cut_post) post2d();
                if (cut_tie) tie_slots();
            }
        }
    }

    union() {
        // rim (perimeter ring), open where the main lead tongues pass (top)
        slab(0, zl) intersection() {
            split_mask(which);
            difference() {
                outline();
                translate([rim_w, rim_w]) square([L - 2 * rim_w, W - 2 * rim_w]);
                if (face == "top") lead_gaps();
                if (face == "bottom") post2d();
            }
        }
        // lip with welding windows
        slab(zl, zs) intersection() {
            split_mask(which);
            difference() {
                outline();
                windows();
                chase2d();
                peg_holes();
                if (face == "bottom") post2d();
            }
        }
        // sockets, split into z-bands for the post pocket and tie slots
        assert(zp < tie_z, "post pocket reaches the tie slots");
        zs_list = [zs, max(zs, zp), tie_z, tie_z + tie_h, zt];
        for (i = [0 : 3]) {
            z0 = zs_list[i]; z1 = zs_list[i + 1];
            if (z1 - z0 > 0.01)
                slab(z0, z1) socket_layer(z1 <= zp + 0.01, i == 2);
        }
    }
}

// ---------------------------------------------------------------------
// Cover plate. Local z = 0 is the OUTER face (print this face down),
// z = lid_t touches the holder rim, pegs point up into the holder.
// ---------------------------------------------------------------------
module groove2d(g) {
    hull() {
        translate([g[0], g[1]]) square([g[4], g[4]], center = true);
        translate([g[2], g[3]]) square([g[4], g[4]], center = true);
    }
}

module label(t, p, size = 4, mirror_y = false) {
    translate(p) mirror([0, mirror_y ? 1 : 0, 0])
        text(t, size = size, halign = "center", valign = "center",
             font = "DejaVu Sans:style=Bold");
}

module lid(face = "top", which = "all") {
    tabs = face == "top" ? top_tabs : bottom_tabs;
    grooves = face == "top" ? top_grooves : bottom_grooves;
    my = face == "bottom";   // bottom lid is read from below -> mirror text

    module through() {
        for (t = tabs) translate([t[0], t[1]]) rotate(t[3]) square(tab_slot, center = true);
        if (face == "top")
            for (l = leads) translate([-1, l[0] - l[2] / 2 - lead_clear]) square([lead_notch + 1, l[2] + 2 * lead_clear]);
        if (face == "bottom") { chase2d(); post2d(); }
    }

    module labels() {
        for (t = (face == "top" ? top_labels : bottom_labels)) label(t[2], [t[0], t[1]], 3.5, my);
        if (face == "top")
            for (l = leads) label(l[1], [lead_notch + 9, l[0]], 6, my);
        label(face == "top" ? "TOP  <- DIVIDER" : "BOTTOM  <- DIVIDER",
              [L / 2 + 40, W - 8], 5, my);
        label("20S4P EVE40P  MAX G3", [L / 2 + 40, 9], 4, my);
    }

    intersection() {
        translate([0, 0, -10]) linear_extrude(lid_t + 20) lid_mask(which);
        union() {
            difference() {
                union() {
                    slab(0, groove_d) difference() { outline(); for (g = grooves) groove2d(g); }
                    slab(groove_d, lid_t) outline();
                }
                translate([0, 0, -1]) linear_extrude(lid_t + 2) through();
                translate([0, 0, -1]) linear_extrude(1 + text_d) labels();
            }
            // locating pegs into the lip holes in the end voids
            for (v = concat(voids_x0, voids_x1))
                if (!(face == "top" && v[0] < lead_notch + peg_d &&
                      min([for (l = leads) abs(l[0] - v[1]) - l[2] / 2]) < peg_d + lead_clear))
                translate([v[0], v[1], lid_t - 0.01])
                    cylinder(d = peg_d, h = rim_h + lip + 1.5, $fn = 24);
        }
    }
}

// ---------------------------------------------------------------------
// Assembly preview (cells, copper, parts in place)
// ---------------------------------------------------------------------
module copper(face) {
    pcs = face == "top" ? top_copper : bottom_copper;
    for (i = [0 : len(pcs) - 1])
        color(i % 2 ? "#d9822b" : "#b5651d") linear_extrude(0.3) polygon(pcs[i]);
}

module assembly(explode = 0) {
    zc0 = lid_t + rim_h + lip;     // cell bottom
    color("#3a7bd5") translate([0, 0, -explode]) lid("bottom");
    color("#555") translate([0, 0, lid_t]) holder_half("bottom");
    translate([0, 0, zc0 - 0.3 - lip + 0.0]) copper("bottom");
    for (c = cells)
        color(c[3] == "+" ? "#2e8b57" : "#2f4f4f")
            translate([c[0], c[1], zc0]) cylinder(d = cell_d, h = cell_len, $fn = 32);
    translate([0, 0, zc0 + cell_len + lip]) copper("top");
    color("#555") translate([0, 0, total_h - lid_t]) mirror([0, 0, 1]) holder_half("top");
    color("#3a7bd5") translate([0, 0, total_h + explode]) mirror([0, 0, 1]) lid("top");
    // deck divider and screw post for reference
    color("#aa3333", 0.6) translate([-10, 0, 0]) cube([10, W, 20]);
    color("#aa3333", 0.6) translate([post_xy[0], post_xy[1], 0]) cylinder(d = post_d, h = post_h);
}

// ---------------------------------------------------------------------
if (part == "holder_bottom")   holder_half("bottom");
if (part == "holder_bottom_a") holder_half("bottom", "a");
if (part == "holder_bottom_b") holder_half("bottom", "b");
if (part == "holder_top")      holder_half("top");
if (part == "holder_top_a")    holder_half("top", "a");
if (part == "holder_top_b")    holder_half("top", "b");
if (part == "lid_bottom")      lid("bottom");
if (part == "lid_bottom_a")    lid("bottom", "a");
if (part == "lid_bottom_b")    lid("bottom", "b");
if (part == "lid_top")         lid("top");
if (part == "lid_top_a")       lid("top", "a");
if (part == "lid_top_b")       lid("top", "b");
if (part == "assembly")        assembly();
if (part == "exploded")        assembly(25);
// documentation views: cover plates as mounted (top seen from above,
// bottom placed on the floor - view it from below)
if (part == "view_lid_top")    mirror([0, 0, 1]) lid("top");
if (part == "view_lid_bottom") lid("bottom");
