// =====================================================================
//  Segway Ninebot Max G3 - 20s4p 21700 cell holder (EVE 40P) + BMS stand
//  Pack envelope 141 x 270 x 81 mm, fits in front of the deck divider,
//  the BMS stands upright on the other side of the divider.
//
//  Cell layout and copper pieces come from layout_data.scad, generated by
//  ../generator/layout.py.
//
//  Coordinates: x = 270 mm length, x = 0 is the DIVIDER end of the pack
//               (the divider is x = -div_w .. 0, the BMS is at x < -div_w)
//               y = 141 mm width,  y = 0 is the side wall the screw post
//                                   is measured from (80 mm)
//               z = height,         z = 0 is the deck floor
//
//  Parts (set `part`, or run export.sh):
//    holder_bottom, holder_top             cell holder halves (one piece, 270 mm)
//    holder_bottom_a/_b, holder_top_a/_b   same, split for beds < 270 mm
//    bms_stand                             holds the ANT BMS upright behind the divider
//    assembly                              everything in place (preview only)
// =====================================================================
include <layout_data.scad>

part = "assembly";

/* [Cell] */
cell_d      = 21.15;  // EVE 40P datasheet: 21.15 +-0.10
cell_len    = 70.6;   // 70.15 +0.15 max + fish-paper ring + margin
cell_bore   = 21.6;   // socket bore: 21.15 cell + 0.45 (0.6 mm web at 22.2 pitch). Also in layout.py
window_d    = 17.0;   // opening in the end stop over every cell. Also in layout.py

/* [Holder] */
cell_recess = 0.6;    // cells sit this far below the holder face (= end-stop lip, 3 layers)
sock        = 9.0;    // socket depth per half
void_d      = 10.0;   // lightening pocket in the empty end spots of the short rows
tie_w       = 4.6;    // zip-tie slot through the end wall (fits 3.6 mm ties)
tie_h       = 2.0;

/* [Screw post] */
post_clear  = 1.0;    // radial clearance
post_extra  = 1.0;    // height clearance

/* [Deck] */
div_w       = 10.0;   // divider width (x)
div_h       = 20.0;   // divider height
post_side   = "bms";  // "bms": post is on the BMS side of the divider, "pack": on the cell side

/* [BMS stand - ANT BMS 24ZHE6-24S-220A] */
bms_l       = 125;    // BMS length
bms_w       = 90;     // BMS width at the connector (head) end = height when standing
bms_body_w  = 70;     // width of the narrow section the power leads come out of
bms_head_l  = 50;     // length of the wide head section (balance connectors on its end)
bms_t       = 16;     // BMS thickness
bms_y       = 70.5;   // centre of the BMS across the deck (y)
bms_head_at = "y1";   // which deck side the connector end faces: "y0" or "y1"
bms_slot    = 0.6;    // clearance in the clamps (thickness)
stand_fin   = 1.8;    // fin / wall thickness
stand_base  = 42;     // base width across the BMS (x) - stops it tipping over
divider_gap = 0.5;    // space between stand and divider

/* [Quality] */
$fn = 48;

// ---------------------------------------------------------------------
L = pack_l;
W = pack_w;
half_h   = cell_recess + sock;
total_h  = cell_len + 2 * cell_recess;
gap_h    = cell_len - 2 * sock;
post_d   = post[2];
post_h   = post[3];
// screw post position: measured from the divider face on its own side
post_xy  = post_side == "pack" ? [post[0], post[1]] : [-div_w - post[0], post[1]];
tie_z    = half_h - 2.5 - tie_h;   // tie slot (local z)
echo(str("PACK HEIGHT = ", total_h, " mm + copper/nickel/insulation (limit 81)  gap between halves = ", gap_h));
assert(total_h <= 78, "pack too tall for 81 mm with copper and insulation");

// ---------------------------------------------------------------------
// 2D helpers
// ---------------------------------------------------------------------
module outline() { square([L, W]); }

module split_mask(which) {
    // which: "all", "a", "b"   (zig-zag split between cells)
    if (which == "a") polygon(split_a);
    else if (which == "b") difference() { translate([-1, -1]) square([L + 2, W + 2]); polygon(split_a); }
    else translate([-1, -1]) square([L + 2, W + 2]);
}

module bores()   { for (c = cells) translate([c[0], c[1]]) circle(d = cell_bore); }
module windows() { for (c = cells) translate([c[0], c[1]]) circle(d = window_d); }
module chase2d() { translate(chase) circle(d = cell_bore); }
module post2d()  {   // open towards the divider end so it never grazes the wall
    hull() for (dx = [0, -post_xy[0] - 1]) translate(post_xy + [dx, 0]) circle(d = post_d + 2 * post_clear);
}
module voids()   { for (v = concat(voids_x0, voids_x1)) translate(v) circle(d = void_d); }
module tie_slots() {
    for (v = voids_x0) translate([-1, v[1] - tie_w / 2]) square([v[0], tie_w]);
}

// 3D slab: linear_extrude a 2D region between z0 and z1
module slab(z0, z1) { translate([0, 0, z0]) linear_extrude(z1 - z0) children(); }

// ---------------------------------------------------------------------
// Holder half. Local coords: z = 0 is the outer face (copper side),
// xy = world xy. Print in this orientation (face down, no supports).
// The cells stop against a thin lip, cell_recess below the face, so the
// punched copper + nickel only has to dip cell_recess to reach the cell.
// ---------------------------------------------------------------------
module holder_half(face = "bottom", which = "all") {
    zs = cell_recess;             // sockets start
    zt = half_h;                  // inner end
    pocket = face == "bottom" && post_side == "pack";
    zp = pocket ? min(zt, post_h + post_extra) : -1;

    module socket_layer(cut_post, cut_tie) {
        intersection() {
            split_mask(which);
            difference() {
                outline();
                bores();
                chase2d();
                voids();
                if (cut_post) post2d();
                if (cut_tie) tie_slots();
            }
        }
    }

    union() {
        // end-stop lip with welding windows
        slab(0, zs) intersection() {
            split_mask(which);
            difference() {
                outline();
                windows();
                chase2d();
                if (pocket) post2d();
            }
        }
        // sockets, split into z-bands for the post pocket and the tie slots
        zl = [zs, max(zs, min(zp, tie_z)), tie_z, tie_z + tie_h, max(tie_z + tie_h, zt)];
        for (i = [0 : 3]) {
            z0 = zl[i]; z1 = zl[i + 1];
            if (z1 - z0 > 0.01)
                slab(z0, z1) socket_layer(pocket && z0 < zp, i == 2);
        }
    }
}

// ---------------------------------------------------------------------
// BMS stand: holds the BMS upright on its long edge (most space
// efficient: only ~45 mm of deck length behind the divider).
//   * head end (balance connectors): low channel along the bottom edge +
//     two side fins that grip the faces only, so the connectors stay free
//   * narrow end: U clamp; a zip tie loops under the narrow section
//     (through holes in the clamp fins) and over its top edge
//   * open base frame with gussets so it cannot tip, notch for the post
// Local coords: y along the BMS (0 = connector end), x across its
// thickness (0 = middle), z up. Prints as is, no supports.
// ---------------------------------------------------------------------
st_x  = -div_w - divider_gap - stand_base / 2;   // world x of the BMS middle
st_y0 = bms_y - bms_l / 2;
body_z0 = (bms_w - bms_body_w) / 2;              // narrow section bottom edge

module bms_shape() {   // the BMS itself, for previews
    translate([-bms_t / 2, 0, 0]) cube([bms_t, bms_head_l, bms_w]);
    translate([-bms_t / 2, bms_head_l, body_z0]) cube([bms_t, bms_l - bms_head_l, bms_body_w]);
}

module stand_local() {
    t  = bms_t + bms_slot;        // slot between the fins
    f  = stand_fin;
    bw = stand_base;
    L  = bms_l;
    rail = 6;
    module fins(y0, y1, h) {
        for (sx = [-1, 1]) translate([sx > 0 ? t / 2 : -t / 2 - f, y0, 0]) cube([f, y1 - y0, h]);
    }
    module gusset(y0, h) {        // triangular brace from a fin down to the rail
        for (sx = [-1, 1]) hull() {
            translate([sx > 0 ? t / 2 : -t / 2 - f, y0, 0]) cube([f, 2.5, h]);
            translate([sx > 0 ? bw / 2 - rail : -bw / 2, y0, 0]) cube([rail, 2.5, 3]);
        }
    }
    difference() {
        union() {
            // base frame
            for (sx = [-1, 1]) translate([sx > 0 ? bw / 2 - rail : -bw / 2, -6, 0]) cube([rail, L + 12, 3]);
            translate([-bw / 2, -6, 0]) cube([bw, 4, 3]);
            translate([-bw / 2, L + 2, 0]) cube([bw, 4, 3]);
            // head end: low channel + side fins + braces
            fins(0, bms_head_l, 10);
            fins(0, 8, 60);
            gusset(0, 45);
            gusset(bms_head_l - 2.5, 8);
            // narrow end: U clamp (two fins + end wall) + braces
            fins(L - 12, L, body_z0 + bms_body_w - 4);
            translate([-t / 2 - f, L, 0]) cube([t + 2 * f, f, body_z0 + bms_body_w - 4]);
            gusset(L - 2.5, 50);
            gusset(L - 12, 20);
        }
        // zip tie: through both clamp fins, under the narrow section
        translate([-bw, L - 9, 3]) cube([2 * bw, tie_w, tie_h + 0.4]);
        // keep the slot clear down to the floor
        translate([-t / 2, 0, -1]) cube([t, L, 200]);
    }
}

module bms_stand() {
    flip = bms_head_at == "y1";
    difference() {
        translate([st_x, flip ? st_y0 + bms_l : st_y0, 0]) mirror([0, flip ? 1 : 0, 0]) stand_local();
        if (post_side == "bms")      // screw post clearance
            translate([post_xy[0], post_xy[1], -1]) cylinder(d = post_d + 2 * post_clear, h = post_h + post_extra + 1);
    }
}

// ---------------------------------------------------------------------
// Assembly preview (cells, copper, parts in place)
// ---------------------------------------------------------------------
module copper(face) {
    pcs = face == "top" ? top_copper : bottom_copper;
    for (i = [0 : len(pcs) - 1])
        color(i % 2 ? "#d9822b" : "#b5651d") linear_extrude(0.3) polygon(pcs[i]);
}

module assembly(explode = 0) {
    zc0 = cell_recess;     // cell bottom
    color("#555") translate([0, 0, -explode]) holder_half("bottom");
    translate([0, 0, -0.3 - explode * 1.5]) copper("bottom");
    for (c = cells)
        color(c[3] == "+" ? "#2e8b57" : "#2f4f4f")
            translate([c[0], c[1], zc0]) cylinder(d = cell_d, h = cell_len, $fn = 32);
    translate([0, 0, total_h + explode * 1.5]) copper("top");
    color("#555") translate([0, 0, total_h + explode]) mirror([0, 0, 1]) holder_half("top");
    color("#3a7bd5") bms_stand();
    flip = bms_head_at == "y1";
    color("#bbb", 0.6) translate([st_x, flip ? st_y0 + bms_l : st_y0, 0]) mirror([0, flip ? 1 : 0, 0]) bms_shape();
    // deck divider and screw post for reference
    color("#aa3333", 0.6) translate([-div_w, 0, 0]) cube([div_w, W, div_h]);
    color("#aa3333", 0.6) translate([post_xy[0], post_xy[1], 0]) cylinder(d = post_d, h = post_h);
}

// ---------------------------------------------------------------------
if (part == "holder_bottom")   holder_half("bottom");
if (part == "holder_bottom_a") holder_half("bottom", "a");
if (part == "holder_bottom_b") holder_half("bottom", "b");
if (part == "holder_top")      holder_half("top");
if (part == "holder_top_a")    holder_half("top", "a");
if (part == "holder_top_b")    holder_half("top", "b");
if (part == "bms_stand")       translate([-st_x + stand_base / 2, -st_y0 + 6, 0]) bms_stand();
if (part == "assembly")        assembly();
if (part == "exploded")        assembly(20);
