// =====================================================================
//  Segway Ninebot Max G3 - 20s4p 21700 cell holder (EVE 40P) + BMS cradle
//  Pack envelope 141 x 270 x 81 mm, fits in front of the deck divider,
//  the BMS cradle sits on the other side of the divider.
//
//  Cell layout and copper pieces come from layout_data.scad, generated by
//  ../generator/layout.py.
//
//  Coordinates: x = 270 mm length, x = 0 is the DIVIDER end of the pack
//               (the divider is x = -div_w .. 0, the BMS is at x < -div_w)
//               y = 141 mm width,  y = 0 is the side wall the screw post
//                                   is measured from (80 mm)
//               z = height,         z = 0 is the deck floor
//
//  Parts (set `part`, or run export.sh):
//    holder_bottom, holder_top             cell holder halves (one piece, 270 mm)
//    holder_bottom_a/_b, holder_top_a/_b   same, split for beds < 270 mm
//    bms_cradle                            tray for the BMS (measure your BMS!)
//    assembly                              everything in place (preview only)
// =====================================================================
include <layout_data.scad>

part = "assembly";

/* [Cell] */
cell_d      = 21.15;  // EVE 40P datasheet: 21.15 +-0.10
cell_len    = 70.6;   // 70.15 +0.15 max + fish-paper ring + margin
cell_bore   = 21.6;   // socket bore: 21.15 cell + 0.45 (0.6 mm web at 22.2 pitch). Also in layout.py
window_d    = 17.0;   // opening in the end stop over every cell. Also in layout.py

/* [Holder] */
cell_recess = 0.6;    // cells sit this far below the holder face (= end-stop lip, 3 layers)
sock        = 9.0;    // socket depth per half
void_d      = 10.0;   // lightening pocket in the empty end spots of the short rows
tie_w       = 4.6;    // zip-tie slot through the end wall (fits 3.6 mm ties)
tie_h       = 2.0;

/* [Screw post] */
post_clear  = 1.0;    // radial clearance
post_extra  = 1.0;    // height clearance

/* [Deck] */
div_w       = 10.0;   // divider width (x)
div_h       = 20.0;   // divider height
post_side   = "bms";  // "bms": post is on the BMS side of the divider, "pack": on the cell side

/* [BMS cradle - PLACEHOLDER SIZES, measure your BMS] */
bms_l       = 125;    // BMS length (along the deck, x)
bms_w       = 70;     // BMS width (across the deck, y)
bms_h       = 25;     // BMS height
bms_y       = 70.5;   // centre of the BMS across the deck (y)
bms_gap     = 1.0;    // clearance around the BMS
cradle_wall = 1.6;
cradle_rise = 12;     // BMS rests this high, clears the 10 mm screw post + wires
cradle_lip  = 8;      // how far the walls rise up the BMS side
divider_gap = 0.5;    // space between cradle and divider

/* [Quality] */
$fn = 48;

// ---------------------------------------------------------------------
L = pack_l;
W = pack_w;
half_h   = cell_recess + sock;
total_h  = cell_len + 2 * cell_recess;
gap_h    = cell_len - 2 * sock;
post_d   = post[2];
post_h   = post[3];
// screw post position: measured from the divider face on its own side
post_xy  = post_side == "pack" ? [post[0], post[1]] : [-div_w - post[0], post[1]];
tie_z    = half_h - 2.5 - tie_h;   // tie slot (local z)
echo(str("PACK HEIGHT = ", total_h, " mm + copper/nickel/insulation (limit 81)  gap between halves = ", gap_h));
assert(total_h <= 78, "pack too tall for 81 mm with copper and insulation");

// ---------------------------------------------------------------------
// 2D helpers
// ---------------------------------------------------------------------
module outline() { square([L, W]); }

module split_mask(which) {
    // which: "all", "a", "b"   (zig-zag split between cells)
    if (which == "a") polygon(split_a);
    else if (which == "b") difference() { translate([-1, -1]) square([L + 2, W + 2]); polygon(split_a); }
    else translate([-1, -1]) square([L + 2, W + 2]);
}

module bores()   { for (c = cells) translate([c[0], c[1]]) circle(d = cell_bore); }
module windows() { for (c = cells) translate([c[0], c[1]]) circle(d = window_d); }
module chase2d() { translate(chase) circle(d = cell_bore); }
module post2d()  {   // open towards the divider end so it never grazes the wall
    hull() for (dx = [0, -post_xy[0] - 1]) translate(post_xy + [dx, 0]) circle(d = post_d + 2 * post_clear);
}
module voids()   { for (v = concat(voids_x0, voids_x1)) translate(v) circle(d = void_d); }
module tie_slots() {
    for (v = voids_x0) translate([-1, v[1] - tie_w / 2]) square([v[0], tie_w]);
}

// 3D slab: linear_extrude a 2D region between z0 and z1
module slab(z0, z1) { translate([0, 0, z0]) linear_extrude(z1 - z0) children(); }

// ---------------------------------------------------------------------
// Holder half. Local coords: z = 0 is the outer face (copper side),
// xy = world xy. Print in this orientation (face down, no supports).
// The cells stop against a thin lip, cell_recess below the face, so the
// punched copper + nickel only has to dip cell_recess to reach the cell.
// ---------------------------------------------------------------------
module holder_half(face = "bottom", which = "all") {
    zs = cell_recess;             // sockets start
    zt = half_h;                  // inner end
    pocket = face == "bottom" && post_side == "pack";
    zp = pocket ? min(zt, post_h + post_extra) : -1;

    module socket_layer(cut_post, cut_tie) {
        intersection() {
            split_mask(which);
            difference() {
                outline();
                bores();
                chase2d();
                voids();
                if (cut_post) post2d();
                if (cut_tie) tie_slots();
            }
        }
    }

    union() {
        // end-stop lip with welding windows
        slab(0, zs) intersection() {
            split_mask(which);
            difference() {
                outline();
                windows();
                chase2d();
                if (pocket) post2d();
            }
        }
        // sockets, split into z-bands for the post pocket and the tie slots
        zl = [zs, max(zs, min(zp, tie_z)), tie_z, tie_z + tie_h, max(tie_z + tie_h, zt)];
        for (i = [0 : 3]) {
            z0 = zl[i]; z1 = zl[i + 1];
            if (z1 - z0 > 0.01)
                slab(z0, z1) socket_layer(pocket && z0 < zp, i == 2);
        }
    }
}

// ---------------------------------------------------------------------
// BMS cradle: an open frame (little plastic) that holds the BMS raised
// above the screw post and the wires. Three thin ribs carry the BMS, the
// walls keep it in place, zip ties go through holes near the top of the
// ribs, and the wall facing the divider is open for the wires.
// Prints as is (walls and ribs straight up, no supports).
// ---------------------------------------------------------------------
cr_l = bms_l + 2 * (bms_gap + cradle_wall);
cr_w = bms_w + 2 * (bms_gap + cradle_wall);
cr_x0 = -div_w - divider_gap - cr_l;          // far end of the cradle
cr_y0 = bms_y - cr_w / 2;
rib_x = [0.12, 0.5, 0.88];                    // rib positions along the cradle

module bms_cradle() {
    t = cradle_wall;
    zt = cradle_rise + cradle_lip;
    translate([cr_x0, cr_y0, 0]) difference() {
        union() {
            // walls (ring)
            difference() {
                cube([cr_l, cr_w, zt]);
                translate([t, t, -1]) cube([cr_l - 2 * t, cr_w - 2 * t, zt + 2]);
            }
            // ribs across the cradle, the BMS sits on their top edge
            for (f = rib_x) translate([f * cr_l - 1, 0, 0]) cube([2, cr_w, cradle_rise]);
        }
        // windows in the long walls below the BMS (saves plastic, wires pass)
        for (i = [0 : 1])
            translate([cr_l * (0.17 + i * 0.38), -1, 2]) cube([cr_l * 0.28, cr_w + 2, cradle_rise - 5]);
        // wire exit in the wall facing the divider (full lip height)
        translate([cr_l - t - 1, t + 4, cradle_rise]) cube([t + 2, cr_w - 2 * t - 8, cradle_lip + 1]);
        // zip-tie holes through the ribs, next to both long walls
        for (f = rib_x) for (sy = [t + 1.5, cr_w - t - 1.5 - tie_w])
            translate([f * cr_l - 2, sy, cradle_rise - 5]) cube([4, tie_w, tie_h + 0.4]);
        // screw post clearance
        if (post_side == "bms")
            translate([post_xy[0] - cr_x0, post_xy[1] - cr_y0, -1])
                cylinder(d = post_d + 2 * post_clear, h = post_h + post_extra + 1);
    }
}

// ---------------------------------------------------------------------
// Assembly preview (cells, copper, parts in place)
// ---------------------------------------------------------------------
module copper(face) {
    pcs = face == "top" ? top_copper : bottom_copper;
    for (i = [0 : len(pcs) - 1])
        color(i % 2 ? "#d9822b" : "#b5651d") linear_extrude(0.3) polygon(pcs[i]);
}

module assembly(explode = 0) {
    zc0 = cell_recess;     // cell bottom
    color("#555") translate([0, 0, -explode]) holder_half("bottom");
    translate([0, 0, -0.3 - explode * 1.5]) copper("bottom");
    for (c = cells)
        color(c[3] == "+" ? "#2e8b57" : "#2f4f4f")
            translate([c[0], c[1], zc0]) cylinder(d = cell_d, h = cell_len, $fn = 32);
    translate([0, 0, total_h + explode * 1.5]) copper("top");
    color("#555") translate([0, 0, total_h + explode]) mirror([0, 0, 1]) holder_half("top");
    color("#3a7bd5") bms_cradle();
    color("#888", 0.4) translate([-div_w + bms_gap * 0, bms_y - bms_w / 2, cradle_rise])
        translate([-divider_gap - cradle_wall - bms_gap - bms_l, 0, 0]) cube([bms_l, bms_w, bms_h]);
    // deck divider and screw post for reference
    color("#aa3333", 0.6) translate([-div_w, 0, 0]) cube([div_w, W, div_h]);
    color("#aa3333", 0.6) translate([post_xy[0], post_xy[1], 0]) cylinder(d = post_d, h = post_h);
}

// ---------------------------------------------------------------------
if (part == "holder_bottom")   holder_half("bottom");
if (part == "holder_bottom_a") holder_half("bottom", "a");
if (part == "holder_bottom_b") holder_half("bottom", "b");
if (part == "holder_top")      holder_half("top");
if (part == "holder_top_a")    holder_half("top", "a");
if (part == "holder_top_b")    holder_half("top", "b");
if (part == "bms_cradle")      translate([-cr_x0, -cr_y0, 0]) bms_cradle();
if (part == "assembly")        assembly();
if (part == "exploded")        assembly(20);
